name: CI (macOS)

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master

jobs:
  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        version:
          - stable
          - beta
          - nightly
        target:
          - x86_64-apple-darwin

    name: ${{ matrix.version }} - ${{ matrix.target }}
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@master

      - name: Install ${{ matrix.version }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.version }}-${{ matrix.target }}
          profile: minimal
          override: true

      - name: Generate lockfile
        uses: actions-rs/cargo@v1
        with:
          command: generate-lockfile
      - name: Cache Cargo directories
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/git
            ~/.cargo/registry
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all -- --nocapture
